### ISSUE TITLE
How to use this lib with a real game engine

### ISSUE THREAD

**Issue by codingwatching** [ShoesForClues/EVE#1]
Hi @ShoesForClues 
I found this EVE is very useful with a lot of function for voxel game
Could you please help me how to using EVE in a particular game engine like Love LUA?
How can I init and setup the world, and where should i get data to render mesh (I mean how to implement how to render world in real game engine)

Thank you so much!

**Comment by ShoesForClues** [comment]
Oh man, this was a really old project. Sorry for the lack of documentation. I can however provide this LÖVE demo program you can look at: [demo.zip](https://github.com/ShoesForClues/EVE/files/9590927/demo.zip) (Bear in mind the demo may be laggy due to my incomplete physics engine and lack of instanced rendering)

Once you create the map and handler objects via ``map.new(...)`` and ``handler.new(map)``, you then add voxel classes with ``handler:add_class(id,type)`` ID being any integer and type being: "blend", "group", or "isolate" which determine how the voxels should be meshed together. "blend" will combine any neighboring solid blocks together that are also "blend" (such as stone, grass, wood etc), "group" will combine blocks only with blocks of the same ID (usually transparent blocks like water, glass or leaves) and "isolate" will prevent blocks from combining at all.

The library itself doesn't provide any rendering code, you must implement that yourself by binding callbacks to the ``mesh_created``, ``mesh_deleted`` and ``mesh_updated`` events using ``handler:register_event(event_name,callback)``

Each of those callbacks receive 5 arguments: ``cx,cy,cz,ci,mesh``
``cx,cy,cz`` are the chunk's position. ``ci`` is the ID of the mesh which you use to keep track of when it gets updated or deleted. And mesh itself is a table which contains the size, position and voxel class of each individual blocks to be rendered. This uses [poor mans greedy meshing](https://www.gamedeveloper.com/programming/the-poor-man-s-voxel-engine) which just naively combines blocks and hides invisible blocks, rather than individually culling every block faces.

I recommend using https://github.com/groverburger/g3d to do the 3D rendering if you don't already have your own renderer.

To generate the map it's recommended to use ``handler:create_chunk(cx,cy,cz,generator)`` with cx,cy and cz again being the chunk position and generator being a simple noise function that takes 3 arguments: ``x,y,z`` and returns a voxel class ID or none at all.

You can then call ``handler:create_voxel(x,y,z,id)`` to add individual blocks or ``handler:delete_voxel(x,y,z)`` to remove blocks.
There is also ``handler:set_voxel_attribute(x,y,z,attribute,value)`` which lets you assign arbitrary values to a given voxel. Say, a chest block which has an "items" attribute that stores a table of items. To retrieve the data back use ``handler:get_voxel_attribute(x,y,z,attribute)``

Now, despite calling ``create_chunk`` and ``create_voxel`` that won't directly invoke the ``mesh_created`` event because you first need to call ``handler:create_mesh(cx,cy,cz)``. This is so you can control what part of the map is visible. Basically have a loop that constantly calls ``handler:create_mesh(...)`` for every chunk near the user's camera, and ``handler:delete_mesh(...)`` for chunks that are too far away from the camera. Don't worry this won't create a mesh every time you call it. 

You then need to call ``handler:update_meshes()`` whenever a voxel or a group of voxels gets updated. This can be called right after you add or delete individual voxels or after updating a large quantity of voxels like a crater from TNT explosions for example.

I hope this helps!

**Comment by codingwatching** [comment]
Hi @ShoesForClues 
Thank you so much for such a detail help! I got some basic ideas after reading your help.
Thank you!
